#cloud-config
users:
  - name: ubuntu
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
  - name: root
    lock_passwd: false
    hashed_passwd: $6$rounds=4096$dlS7oUlBJqLhuO1E$DhJ8oT.JjXmYHQSjST.ZDWyqP4TbrgXzt6zOAh8Nhbvkwm64qTRmMG09CpZx5iCGIAZmFdsxlqtZWKNLogAZy0

chpasswd:
  list: |
    root:test123
    ubuntu:ubuntu
  expire: False

ssh_pwauth: True

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent

write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          ens3:
            dhcp4: no
            addresses:
              - ${net_prefix}.${IP_addr}/24
            gateway4: ${net_prefix}.1
            nameservers:
              addresses:
                - 8.8.8.8
                - 8.8.4.4
runcmd:
  - apt-get update
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - netplan apply
  - swapoff --all
